# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Farmily' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Farmily

pod 'Moya/RxSwift', '~> 15.0'
pod 'IQKeyboardManagerSwift'
pod 'SnapKit', '~> 5.6.0'
pod 'Then'
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'
pod 'Kingfisher', '~> 7.0'
pod 'Moya', '~> 15.0'


end
